# Archivo nginx.conf
events {}

http {
    server {
        listen 80;
        server_name localhost 3.211.186.69 test.guayini.com 10.0.13.6 0.0.0.0/0 ;

        location /static/ {
            alias /GUAYINI/statics/;  # Ruta a los archivos estáticos de Django
        }

        location / {
            proxy_pass http://localhost:8000;  # Nombre del servicio de Django
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
