"""
Django settings for GUAYINI project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Configuración para django-background-tasks
from datetime import timedelta
#from . import tasks


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!)yye$n)u_k822e=1w!m_8v-1pe*f79mhjb@-1=04+q+=8x!u+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['https://guayini.com']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap_datepicker_plus',
    'django_crontab',
    #'celery',
    'huey.contrib.djhuey',
    'tasks'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GUAYINI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GUAYINI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'guayinidb',
        'USER': 'postgres',
        'PASSWORD': 'yM8Q4xrlp5obNDPvnyL5',
        'HOST': 'guayinidb.guayini.com',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'GUAYINI/static/')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'GUAYINI/static')]


LOGIN_URL = '/signin'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TWILIO_ACCOUNT_SID = 'ACbf4a36af7fd22a108ea2b6f90eddf472'
TWILIO_AUTH_TOKEN = '02ed70a65c291555d65e29087b5ec770'
TWILIO_ACCOUNT_SID_PRUEBA = 'AC46f6825baf82b2cfc8052caf8a220fd8'
TWILIO_AUTH_TOKEN_PRUEBA = '899671c0580d3806006063ede7de6b05'
TWILIO_WHATSAPP_NUMBER = '+14155238886'
TWILIO_COETEC_NUMBER = '+5493518008514'
TWILIO_CONTACT_TEMPLATE = 'Bienvenido a Guayini. Usted empezara a recibir notificaciones desde este numero. Saludos'
MESSAGEBIRD_ACCESS_KEY = '7eBPqOuOnBEPcKXQWy0PdEyXM'
MESSAGEBIRD_COETEC_NUMBER = '+5493518008514'
MESSAGEBIRD_CHANNEL_ID = '3cb926d1-6926-457a-ac06-fa4c42bfefe5'
MESSAGEBIRD_CHANNEL_ID_SECONDARY = '779e3365-f297-451c-a74b-b3ffa91c3fe7'
MESSAGEBIRD_ORIGINATOR = '5493518008514'
FACEBOOK_AUTH_TOKEN = 'EAAJEmjUBMUABAN8XG7ZAUVJsGKvYHp28DqcZBe0lZCI2BRGkZB4nX3UIvjtmoLZA7YBFe5EDf24JNiyON0Lv6dxBgdH9ZA0zf5TkLH5DzgsCdwJTVGwyspZCFtjqytjuEBXh6kWZAPtbrG7rirwdfYkd6ZBlthURgQc4gjGhJsuKT1dPZCmaUE7Qp1'
# NUMERO GUAYINI:  +54 9 3515 99-3031
FACEBOOK_SENDER_NUMBER_1 = 102289356257975


# CRON JOBS
CRONJOBS = [    ('*/1 * * * *', 'tasks.cron.test_cron_job')]
CRONJOB_SCHEDULE = CRONJOBS

