# Generated by Django 4.1.7 on 2023-03-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_datecompleted_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='adress',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
