# Generated by Django 4.1.7 on 2023-03-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_whatsappgroup_phonegroup_phone_mailgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='adress',
            field=models.TextField(blank=True),
        ),
    ]
