# Generated by Django 4.1.7 on 2023-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_mail_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateprogramed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='adress',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
