# Generated by Django 4.1.7 on 2023-04-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_dateprogramed_alter_mail_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='to',
            field=models.TextField(blank=True),
        ),
    ]
