# Generated by Django 4.1.7 on 2023-05-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCronjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
