# Generated by Django 4.1.7 on 2023-05-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_testcronjob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCronjob',
            new_name='Test',
        ),
    ]
