# Generated by Django 4.1.7 on 2023-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.TextField(blank=True),
        ),
    ]
