# Generated by Django 4.1.7 on 2023-07-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sender',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='wamID',
            field=models.TextField(blank=True),
        ),
    ]
