# Generated by Django 4.1.7 on 2023-07-20 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0013_task_sender_task_status_task_type_task_wamid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='Type',
        ),
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('bot_id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=100)),
                ('activator', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
