# Generated by Django 4.1.7 on 2023-08-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='bots',
            name='response_buttons',
            field=models.TextField(blank=True),
        ),
    ]
