# Generated by Django 4.1.7 on 2023-08-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_bots_level_bots_lft_bots_parent_bots_rght_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='created',
            field=models.DateTimeField(auto_now_add=True,  blank=True),
        ),
        migrations.AddField(
            model_name='bots',
            name='created',
            field=models.DateTimeField(auto_now_add=True,  blank=True),

        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True,  blank=True),
        ),
    ]
