# Generated by Django 4.1.7 on 2023-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_accesstoken_created_alert_created_bots_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
