# Generated by Django 4.1.7 on 2023-09-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_mail_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='groups',
            field=models.TextField(blank=True),
        ),
    ]
