# Generated by Django 4.1.7 on 2023-09-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_mail_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='groups',
        ),
        migrations.AddField(
            model_name='mail',
            name='groups',
            field=models.ManyToManyField(blank=True, to='tasks.mailgroup'),
        ),
    ]
