# Generated by Django 4.1.7 on 2023-09-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_remove_mail_groups_mail_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='groups',
        ),
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(blank=True, to='tasks.whatsappgroup'),
        ),
    ]
