# Generated by Django 4.1.7 on 2023-09-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_remove_task_groups_task_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
