# Generated by Django 4.1.7 on 2023-09-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_phone_datecompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='subject',
        ),
        migrations.AddField(
            model_name='phone',
            name='to',
            field=models.TextField(blank=True),
        ),
    ]
