# Generated by Django 4.1.7 on 2023-09-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_remove_phone_adress_remove_phone_subject_phone_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='groups',
            field=models.ManyToManyField(blank=True, to='tasks.phonegroup'),
        ),
    ]
