# Generated by Django 4.1.7 on 2023-09-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_whatsappalert_phonealert_mailalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappalert',
            name='groups',
            field=models.ManyToManyField(blank=True, to='tasks.whatsappgroup'),
        ),
    ]
