# Generated by Django 4.1.7 on 2023-09-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_whatsappalert_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappalert',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappalert',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
