# Generated by Django 4.1.7 on 2023-10-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_whatsappalert_last_sent_whatsappalert_sent_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailalert',
            name='groups',
            field=models.ManyToManyField(blank=True, to='tasks.mailgroup'),
        ),
        migrations.AddField(
            model_name='mailalert',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailalert',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonealert',
            name='groups',
            field=models.ManyToManyField(blank=True, to='tasks.phonegroup'),
        ),
        migrations.AddField(
            model_name='phonealert',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonealert',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
