# Generated by Django 4.1.7 on 2023-10-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_mailalert_groups_mailalert_last_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailalert',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
